name: Deployment Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Use variables
        run: |
          echo "AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}"
          echo "AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}"
          echo "AWS_PUBLIC_KEY: ${{ secrets.AWS_PUBLIC_KEY }}"
          echo "AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}"
          echo "DB_HOST: ${{ secrets.DB_HOST }}"
          echo "DB_USER: ${{ secrets.DB_USER }}"
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
          echo "DB_NAME: ${{ secrets.DB_NAME }}"
          echo "EMAIL_HOST: ${{ secrets.EMAIL_HOST }}"
          echo "EMAIL_USER: ${{ secrets.EMAIL_USER }}"
          echo "EMAIL_PASS: ${{ secrets.EMAIL_PASS }}"
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
          AWS_PUBLIC_KEY: ${{ secrets.AWS_PUBLIC_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      - name: Run tests
        working-directory: ./backend
        run: npm run test
